spring.application.name=recommendationService
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/recommendation_rules
spring.datasource.username=postgres
spring.datasource.password=240398
spring.datasource.driver-class-name=org.postgresql.Driver

knowledge.datasource.url=jdbc:h2:file:C:/database/transaction;ACCESS_MODE_DATA=r;IFEXISTS=TRUE
knowledge.datasource.username=
knowledge.datasource.password=
knowledge.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log = classpath:db/changelog/db.changelog-master.yaml
telegram.bot.token=${TELEGRAM_BOT_TOKEN}