spring.application.name=recommendationService
spring.datasource.url=jdbc:h2:file:C:/database/transaction;ACCESS_MODE_DATA=r;IFEXISTS=TRUE
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.hikari.read-only=true
server.port=8080